/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarEmpleado.java
 *
 * Created on 03-dic-2012, 11:17:30
 */

package FORMS;

import CLASES.Empleado;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonzalo
 */
public class BuscarEmpleado extends javax.swing.JInternalFrame {

    /** Creates new form BuscarEmpleado */
    public BuscarEmpleado() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Paterno"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaEmpleadoMouseClicked(evt);
            }
        });
        tablaEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaEmpleadoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaEmpleado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 390, 330));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("BUSCAR EMPLEADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carbon Fiber 1600x1000.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Empleado empleado = new Empleado();
            ResultSet reg = empleado.buscarPorNombre(txtBuscar.getText());
            String[] columnNames = new  String[]{"Codigo","Nombre","Paterno"};
            Object[][]data = new Object[25][7];
            int i = 0;
            while (reg.next()){
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getString(3);
                    i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablaEmpleado.setModel(tabla);
        }catch(Exception e){}
    }//GEN-LAST:event_btnBuscarActionPerformed

    public JTextField txtEmpleado;
    public JTextField txtCodEmpleado;
    private void tablaEmpleadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaEmpleadoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            if (evt.getKeyCode() == 10) {
                int fila = tablaEmpleado.getSelectedRow();
                if (fila >= 0 && tablaEmpleado.getValueAt(fila, 0) != null) {
                    txtCodEmpleado.setText(String.valueOf(tablaEmpleado.getValueAt(fila, 0)));
                    txtEmpleado.setText((String) tablaEmpleado.getValueAt(fila, 1));
                    this.dispose();
                } else {
                    txtCodEmpleado.setText("");
                    txtEmpleado.setText("");
                }
            }
        }
    }//GEN-LAST:event_tablaEmpleadoKeyPressed

    private void tablaEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaEmpleadoMouseClicked
        // TODO add your handling code here:
        int fila = tablaEmpleado.getSelectedRow();
                if (fila >= 0 && tablaEmpleado.getValueAt(fila, 0) != null) {
                    txtCodEmpleado.setText(String.valueOf(tablaEmpleado.getValueAt(fila, 0)));
                    txtEmpleado.setText((String) tablaEmpleado.getValueAt(fila, 1));
                    this.dispose();
                } else {
                    txtCodEmpleado.setText("");
                    txtEmpleado.setText("");
                }
    }//GEN-LAST:event_tablaEmpleadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
