/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BuscarProvedor.java
 *
 * Created on 07-dic-2012, 12:50:59
 */

package FORMS;

import CLASES.Proveedor;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AGUAYO
 */
public class BuscarProvedor extends javax.swing.JInternalFrame {

    /** Creates new form BuscarProvedor */
    public BuscarProvedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproveedor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaproveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaproveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaproveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaproveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, 385, 206));

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 106, -1, -1));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Buscar();
    }//GEN-LAST:event_jButton1ActionPerformed
public JTextField txtProveedor;
public JTextField txtProveedorCodigo;
    private void tablaproveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaproveedorMouseClicked
        // TODO add your handling code here:
        int fila = tablaproveedor.getSelectedRow();
        if(fila >= 0 && tablaproveedor.getValueAt(fila, 0) != null) {
            txtProveedorCodigo.setText(String.valueOf(tablaproveedor.getValueAt(fila, 0)));
            txtProveedor.setText((String)tablaproveedor.getValueAt(fila, 1));
            this.dispose();
        } else {
            txtProveedorCodigo.setText("");
            txtProveedor.setText("");
        }
    }//GEN-LAST:event_tablaproveedorMouseClicked
public void Buscar(){
        try{
            Proveedor prov = new Proveedor();
            ResultSet reg = prov.traerProveedor(txtBuscar.getText());
            String[] columnNames = new  String[]{"Codigo","Nombre","Nit","Direccion","Telefono","Laboratorio"};
            Object[][]data = new Object[25][6];
            int i = 0;
            while (reg.next()){
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getString(3);
                    data[i][3] = reg.getString(4);
                    data[i][4] = reg.getString(5);
                    data[i][5] = reg.getInt(6);
                    i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablaproveedor.setModel(tabla);
        }catch(Exception e){}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaproveedor;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
