package FORMS;


import CLASES.Categoria;
import CLASES.Cliente;
import CLASES.Medicamento;
import CLASES.Venta;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gonzalo
 */
public class BuscarMedicamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCliente
     */
    public BuscarMedicamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicamento = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        rbSinCategoria = new javax.swing.JRadioButton();
        rbCategoria = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox();
        btnInicializar = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tablaMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaMedicamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaMedicamentoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMedicamento);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        rbSinCategoria.setText("Sin Categoria");
        rbSinCategoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbSinCategoriaStateChanged(evt);
            }
        });
        rbSinCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSinCategoriaActionPerformed(evt);
            }
        });

        rbCategoria.setText("Categoria");
        rbCategoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chequedCategoria(evt);
            }
        });

        btnInicializar.setText("Inicio");
        btnInicializar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicializarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbSinCategoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)))
                                .addGap(33, 33, 33)
                                .addComponent(btnBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(btnInicializar)
                                .addGap(2, 2, 2)
                                .addComponent(jComboBox1, 0, 154, Short.MAX_VALUE)))
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCategoria)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInicializar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSinCategoria)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public void Buscar() {
        try {
            
            Medicamento medicamento=new Medicamento();
            int key = ((Categoria) jComboBox1.getSelectedItem()).Codigo();
            boolean sw=false;
            if(jComboBox1.getItemCount() != 0){sw=true;}
            ResultSet reg = medicamento.traerMedicamento(txtBuscar.getText(), String.valueOf(key),sw);
            String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
            Object[][] data = new Object[4][10];
            int i = 0;
            while (reg.next()) {
                data[i][0] = reg.getInt(1);
                data[i][1] = reg.getString(2);
                data[i][2] = reg.getDouble(3);
                data[i][3] = reg.getInt(4);
                i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablaMedicamento.setModel(tabla);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
            Buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaMedicamentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaMedicamentoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaMedicamentoKeyPressed

    private void rbSinCategoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbSinCategoriaStateChanged
        // TODO add your handling code here:
        rbCategoria.setSelected(false);
        
    }//GEN-LAST:event_rbSinCategoriaStateChanged

    private void chequedCategoria(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chequedCategoria
        // TODO add your handling code here:
        rbSinCategoria.setSelected(false);
        
    }//GEN-LAST:event_chequedCategoria

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnInicializarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicializarActionPerformed
        // TODO add your handling code here:
        try{
            Categoria c = new Categoria();
            ResultSet reg = c.traerCategoria();
            while(reg.next()){
                  jComboBox1.addItem(new Categoria(reg.getInt(1), reg.getString(2)));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }//GEN-LAST:event_btnInicializarActionPerformed

    private void rbSinCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSinCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSinCategoriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInicializar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbCategoria;
    private javax.swing.JRadioButton rbSinCategoria;
    private javax.swing.JTable tablaMedicamento;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
