package FORMS;


import CLASES.Cliente;
import CLASES.Venta;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gonzalo
 */
public class BuscarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablacliente = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setTitle("Buscar Cliente");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablacliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacliente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablacliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaclienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablacliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 380, 240));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 260, 20));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscarC.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 40));

        jLabel1.setForeground(new java.awt.Color(102, 255, 0));
        jLabel1.setText("Buscar Cliente ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setBackground(new java.awt.Color(43, 186, 186));
        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24));
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("BUSCAR CLIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 190, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carbon Fiber 1600x1000.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void Buscar(){
        try{
            Cliente cliente = new Cliente();
            ResultSet reg = cliente.traerCliente(txtBuscar.getText());
            String[] columnNames = new  String[]{"Codigo","Nombre","Apellidos"};
            Object[][]data = new Object[25][3];
            int i = 0;
            while (reg.next()){
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getString(3);
                    i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablacliente.setModel(tabla);
        }catch(Exception e){}
}

public JTextField txtCliente;
public JTextField txtClienteCodigo;
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
            Buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaclienteMouseClicked
        // TODO add your handling code here:
        //if(evt.getKeyCode()==10){
        int fila = tablacliente.getSelectedRow();
        if(fila >= 0 && tablacliente.getValueAt(fila, 0) != null)
        {
            txtClienteCodigo.setText(String.valueOf(tablacliente.getValueAt(fila, 0)));
            txtCliente.setText((String)tablacliente.getValueAt(fila, 1));
            this.dispose();
        }
        else
        {
            txtClienteCodigo.setText("");
            txtCliente.setText("");
        }
    }//GEN-LAST:event_tablaclienteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacliente;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
