/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formCliente.java
 *
 * Created on 02-dic-2012, 16:20:32
 */

package FORMS;

import CLASES.Cliente;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonzalo
 */
public class formCliente extends javax.swing.JInternalFrame {

    /** Creates new form formCliente */
    public formCliente() {
        initComponents();
        txtCod.setVisible(false);
        lblcod.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBuscar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtCod = new javax.swing.JTextField();
        lblcod = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        setTitle("Registro Empleado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, -1));

        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete v2.png"))); // NOI18N
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 30));

        jbtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Writing pencil.png"))); // NOI18N
        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, 30));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit (Spencil).png"))); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36));
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("REGISTRO CLIENTE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 360, -1));

        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Paterno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Materno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Correo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, -1));
        getContentPane().add(txtPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, -1));
        getContentPane().add(txtMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 160, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 160, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 160, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 260, -1));

        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Save file.png"))); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 30));

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Paterno", "Materno", "Direccion", "Telefono", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaClienteKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);
        tablaCliente.getColumnModel().getColumn(0).setMaxWidth(45);
        tablaCliente.getColumnModel().getColumn(5).setMaxWidth(75);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 650, 340));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Paterno");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jRadioButton2.setText("Nombre");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 60, -1));

        lblcod.setForeground(new java.awt.Color(255, 51, 0));
        lblcod.setText("Codigo");
        getContentPane().add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label.setForeground(new java.awt.Color(255, 51, 0));
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carbon Fiber 1600x1000.jpg"))); // NOI18N
        label.setText("jLabel8");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtBuscarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtPaterno.setText("");
        txtMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");

    }//GEN-LAST:event_jbtnNuevoActionPerformed

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
        Cliente clt=new Cliente();
        clt.Nombre(txtNombre.getText());
        clt.Paterno(txtPaterno.getText());
        clt.Materno(txtMaterno.getText());
        clt.Direccion(txtDireccion.getText());
        clt.Telefono(txtTelefono.getText());
        clt.Correo(txtCorreo.getText());
        clt.Guardar();
        JOptionPane.showMessageDialog(null, "Se guardo satisfactoriamente");
        jbtnBuscarActionPerformed(evt);
    }//GEN-LAST:event_jbtnGuardarActionPerformed


    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Cliente cliente = new Cliente();
            ResultSet reg = cliente.BuscarPorNOmbre(txtBuscar.getText());
            String[] columnNames = new  String[]{"Codigo","Nombre","Paterno","Materno","Direccion","Telefono","Correo"};
            Object[][]data = new Object[25][7];
            int i = 0;
            while (reg.next()){
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getString(3);
                    data[i][3] = reg.getString(4);
                    data[i][4] = reg.getString(5);
                    data[i][5] = reg.getString(6);
                    data[i][6] = reg.getString(7);
                    i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablaCliente.setModel(tabla);
        }catch(Exception e){}

    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        // TODO add your handling code here:
        Cliente clt=new Cliente();
        clt.Codigo(Integer.parseInt(txtCod.getText()));
        clt.Nombre(txtNombre.getText());
        clt.Paterno(txtPaterno.getText());
        clt.Materno(txtMaterno.getText());
        clt.Direccion(txtDireccion.getText());
        clt.Telefono(txtTelefono.getText());
        clt.Correo(txtCorreo.getText());
        clt.Modificar();
        jbtnBuscarActionPerformed(evt);
        JOptionPane.showMessageDialog(null, "Modificacion Correcta!!!");
        txtCod.setVisible(false); lblcod.setVisible(false);

    }//GEN-LAST:event_jbtnModificarActionPerformed
    
    private void tablaClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaClienteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtCod.setVisible(true);
            lblcod.setVisible(true);
            int fila = tablaCliente.getSelectedRow();
            if (fila >= 0 && tablaCliente.getValueAt(fila, 0) != null) {
                txtCod.setText(String.valueOf(tablaCliente.getValueAt(fila, 0)));
                txtNombre.setText((String) tablaCliente.getValueAt(fila, 1));
                txtPaterno.setText((String) tablaCliente.getValueAt(fila, 2));
                txtMaterno.setText((String) tablaCliente.getValueAt(fila, 3));
                txtDireccion.setText((String) tablaCliente.getValueAt(fila, 4));
                txtTelefono.setText((String) tablaCliente.getValueAt(fila, 5));
                txtCorreo.setText((String) tablaCliente.getValueAt(fila, 6));

                //this.dispose();
            } else {
                label.setText("");
                txtNombre.setText("");
                txtPaterno.setText("");
                txtMaterno.setText("");
                txtDireccion.setText("");
                txtTelefono.setText("");
                txtCorreo.setText("");
            }
        }

    }//GEN-LAST:event_tablaClienteKeyPressed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        Cliente clt=new Cliente();
        clt.Codigo(Integer.parseInt(txtBuscar.getText()));
        clt.Eliminar();
        txtBuscar.setText("");
        jbtnBuscarActionPerformed(evt);
    }//GEN-LAST:event_jbtnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblcod;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
