/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormCompras.java
 *
 * Created on 07-dic-2012, 13:00:14
 */

package FORMS;

import CLASES.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AGUAYO
 */
public class FormCompras extends javax.swing.JInternalFrame {

    /** Creates new form FormCompras */
    public FormCompras() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProveedor = new javax.swing.JButton();
        btnEmpleado2 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        txtProveedor = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        txtEmpleadoCodigo = new javax.swing.JTextField();
        txtProveedorCodigo = new javax.swing.JTextField();
        txtCodEmpleado = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicamento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblhora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Proveedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        btnProveedor.setText("Proveedor");
        btnProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        btnEmpleado2.setText("Empleado");
        btnEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleado2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));
        getContentPane().add(txtProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 20));
        getContentPane().add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 20));
        getContentPane().add(txtEmpleadoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        getContentPane().add(txtProveedorCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(txtCodEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 350, -1));

        tablaMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicamentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMedicamento);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 110));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaDetalle);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, 110));
        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 430, 470));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, -1));

        jLabel2.setText("Empleado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 60, -1));

        lblhora.setText("FECHA");
        getContentPane().add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jButton1.setText("Crear Categoria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jButton2.setText("Crear Medicamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jButton3.setText("Recargar Categoria");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int codprovee;
private int codEmpleado;
private int codcompra;
    public void Buscar() {
        Medicamento medicamento = new Medicamento();
        boolean sw = false;
        if (jComboBox1.getItemCount() > 1) {
            sw = true;
            try {
                if(jComboBox1.getSelectedItem()=="Ninguno")
                {
                    String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                    int i=0;
                    Object[][] data = new Object[25][4];
                    while(i<25){
                     data[i][0] = "";
                    data[i][1] = "";
                    data[i][2] = "";
                    data[i][3] = "";
                    i++;
                    }
                    DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);
                }
                else{
                int key = ((Categoria) jComboBox1.getSelectedItem()).Codigo();
                ResultSet reg = medicamento.traerMedicamento(txtBuscar.getText(), String.valueOf(key), sw);
                String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                Object[][] data = new Object[500][4];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getDouble(3);
                    data[i][3] = reg.getInt(4);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);}

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }

    ArrayList lista = new ArrayList();
    public void SeleccionarAlDetalle() {
        int fila = tablaMedicamento.getSelectedRow();
        if (fila < 0 && !lista.contains(tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0))) {
            return;
        }
        Object[][] data = new Object[tablaDetalle.getRowCount() + 1][5];
        int i = 0;
        while (i < tablaDetalle.getRowCount()) {
            data[i][0] = tablaDetalle.getValueAt(i, 0);
            data[i][1] = tablaDetalle.getValueAt(i, 1);
            data[i][2] = tablaDetalle.getValueAt(i, 2);
            data[i][3] = tablaDetalle.getValueAt(i, 3);
            data[i][4] = tablaDetalle.getValueAt(i, 4);
            i++;
        }
        if (!lista.contains(tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0))) {
            lista.add(tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0));
            data[i][0] = tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0);
            data[i][1] = tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 1);
            data[i][2] = tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 2);
            data[i][3] = 1;
        } else {
            return;//new Object[][]{}
        }
        String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Cantidad","Sub Total"};
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
                data, columnNames) {

            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class,java.lang.Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }

    public void buscar2(){
        try{
            Medicamento medicamento =new Medicamento();
            ResultSet reg = medicamento.traerMed(txtBuscar.getText());
                String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                Object[][] data = new Object[500][4];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getDouble(3);
                    data[i][3] = reg.getInt(4);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);}

            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }
    Medicamento m = new Medicamento();
    Compra compra = new Compra();
    DetalleCompra detalle = new DetalleCompra();
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        cargarcat();
    }//GEN-LAST:event_formInternalFrameOpened
    void cargarcat() {
        try {
            Categoria c = new Categoria();
            jComboBox1.addItem("Ninguno");
            ResultSet reg = c.traerCategoria();
            while (reg.next()) {
                jComboBox1.addItem(new Categoria(reg.getInt(1), reg.getString(2)));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void btnProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedorActionPerformed
        // TODO add your handling code here:
        BuscarProvedor f = new BuscarProvedor();
        f.txtProveedor = this.txtProveedor;
        f.txtProveedorCodigo = this.txtProveedorCodigo;
        jDesktopPane2.add(f);
        f.show(true);
    }//GEN-LAST:event_btnProveedorActionPerformed

    private void btnEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleado2ActionPerformed
        // TODO add your handling code here:
        BuscarEmpleado fe=new BuscarEmpleado();
        fe.txtEmpleado=this.txtEmpleado;
        fe.txtCodEmpleado = this.txtCodEmpleado;
        jDesktopPane2.add(fe);
        fe.show(true);
    }//GEN-LAST:event_btnEmpleado2ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
         if(tablaDetalle.getRowCount() > 0){
            compra.cod_provee(Integer.parseInt(txtProveedorCodigo.getText()));
            compra.Cod_emp(Integer.parseInt(txtCodEmpleado.getText()));
            compra.Guardar();
            int i = 0;
            while(i < tablaDetalle.getRowCount()){
                detalle.CodigoMedicamento(Integer.parseInt(String.valueOf(tablaDetalle.getValueAt(i,0))));
                detalle.Cantidad(Integer.parseInt(String.valueOf(tablaDetalle.getValueAt(i,3))));
                detalle.Costo(Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2))));
                detalle.Guardar();
                i++;
            }
            JOptionPane.showMessageDialog(null, "Venta Realizada Correctamente");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem()=="Ninguno"){
            buscar2();
        } else{
            Buscar();}
        if(txtBuscar.getText().length()==0){
            String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
            int i=0;
            Object[][] data = new Object[50][4];
            while(i<50){
                data[i][0] = "";
                data[i][1] = "";
                data[i][2] = "";
                data[i][3] = "";
                i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablaMedicamento.setModel(tabla);
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tablaMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicamentoMouseClicked
        // TODO add your handling code here:
        SeleccionarAlDetalle();
        int i = 0;
        double total=0;
        while(i < tablaDetalle.getRowCount()){
            total += Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2)));
            tablaDetalle.setValueAt(Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2))), i, 4);
            i++;
        }
        txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_tablaMedicamentoMouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        txtBuscar.setText("");
        Buscar();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Ccat cc = new Ccat();
        jDesktopPane2.add(cc);
        cc.show(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Cmed cm = new Cmed();
        jDesktopPane2.add(cm);
        cm.show(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        cargarcat();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpleado2;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnProveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaMedicamento;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodEmpleado;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtEmpleadoCodigo;
    private javax.swing.JTextField txtProveedor;
    private javax.swing.JTextField txtProveedorCodigo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
