/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formMedicamento.java
 *
 * Created on 03-dic-2012, 1:56:00
 */

package FORMS;
import CLASES.Categoria;
import CLASES.Medicamento;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gonzalo
 */
public class formMedicamento extends javax.swing.JInternalFrame {

    /** Creates new form formMedicamento */
    public formMedicamento() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnGuardar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMedicamentdo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        txtcategoria = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jbtnEliminar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCategoria = new javax.swing.JTable();
        txtcat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcod = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Stock");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 100, 30));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, 20));

        tablaMedicamentdo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Stock", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedicamentdo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicamentdoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaMedicamentdo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 530, 200));

        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Buscar Medicamento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 36));
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("REGISTRO MEDICAMENTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel7.setForeground(new java.awt.Color(102, 204, 0));
        jLabel7.setText("Precio");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel9.setForeground(new java.awt.Color(102, 204, 0));
        jLabel9.setText("Nombre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        getContentPane().add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 160, -1));
        getContentPane().add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 160, -1));
        getContentPane().add(txtcategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 160, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 30));

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 100, 30));

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 100, 30));

        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 100, 30));

        TablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cod_Cat", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCategoriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaCategoria);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, 170));

        txtcat.setEnabled(false);
        getContentPane().add(txtcat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 30, -1));

        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("Categoria");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtcod.setEnabled(false);
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 30, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
        Medicamento med=new Medicamento();
        med.Nombre(txtNombre.getText());
        med.Precio(Double.parseDouble(txtprecio.getText()));
        med.Stock(Integer.parseInt(txtstock.getText()));
        med.Categoria(Integer.parseInt(txtcategoria.getText()));
        med.Guardar();
}//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        // TODO add your handling code here:
        Medicamento med=new Medicamento();
        med.Codigo(Integer.parseInt(txtcod.getText()));
        med.Nombre(txtNombre.getText());
        med.Precio(Double.parseDouble(txtprecio.getText()));
        med.Stock(Integer.parseInt(txtstock.getText()));
        med.Categoria(Integer.parseInt(txtcat.getText()));
        med.Modificar();
}//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        txtNombre.setText("");
        txtcat.setText("");
        txtstock.setText("");
        txtprecio.setText("");
        txtcategoria.setText("");
}//GEN-LAST:event_jbtnNuevoActionPerformed
void buscar(){
    try {
                Medicamento med = new Medicamento();
                ResultSet reg = med.buscarmedicamento(txtBuscar.getText());
                String[] columnNames = new String[]{"Codigo", "Nombre", "Stock", "Precio", "Categoria"};
                Object[][] data = new Object[150][5];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getString(3);
                    data[i][3] = reg.getString(4);
                    data[i][4] = reg.getString(5);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamentdo.setModel(tabla);
            } catch (Exception e) {
        }
}
    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
            buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tablaMedicamentdoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicamentdoMouseClicked
        // TODO add your handling code here:
        int fila = tablaMedicamentdo.getSelectedRow();
            if (fila >= 0 && tablaMedicamentdo.getValueAt(fila, 0) != null) {
                txtcod.setText(String.valueOf(tablaMedicamentdo.getValueAt(fila, 0)));
                txtNombre.setText((String) tablaMedicamentdo.getValueAt(fila, 1));
                txtprecio.setText((String) tablaMedicamentdo.getValueAt(fila, 2));
                txtstock.setText((String) tablaMedicamentdo.getValueAt(fila, 3));
                txtcat.setText((String) tablaMedicamentdo.getValueAt(fila, 4));
            } else {
                txtcod.setText("");
                txtNombre.setText("");
                txtprecio.setText("");
                txtstock.setText("");
                txtcat.setText("");
                txtcategoria.setText("");
            }
        buscat();
    }//GEN-LAST:event_tablaMedicamentdoMouseClicked

    public void buscat(){
        try {
                Categoria cat = new Categoria();
                ResultSet reg = cat.traerCategoria();
                String[] columnNames = new String[]{"Codigo", "Categoria"};
                Object[][] data = new Object[30][2];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                TablaCategoria.setModel(tabla);
            } catch (Exception e) {
        }
    }
    private void TablaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCategoriaMouseClicked
        // TODO add your handling code here:
        int fila = TablaCategoria.getSelectedRow();
            if (fila >= 0 && TablaCategoria.getValueAt(fila, 0) != null) {
                txtcat.setText(String.valueOf(TablaCategoria.getValueAt(fila, 0)));
                txtcategoria.setText((String) TablaCategoria.getValueAt(fila, 1));
            } else {
                txtcod.setText("");
                txtNombre.setText("");
                txtprecio.setText("");
                txtstock.setText("");
                txtcat.setText("");
                txtcategoria.setText("");
            }
    }//GEN-LAST:event_TablaCategoriaMouseClicked

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        Medicamento med=new Medicamento();
        med.Codigo(Integer.parseInt(txtcod.getText()));
        med.Eliminar();
    }//GEN-LAST:event_jbtnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JTable tablaMedicamentdo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcat;
    private javax.swing.JTextField txtcategoria;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables

}
