/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formproveedor.java
 *
 * Created on 03-12-2012, 08:35:04 PM
 */

package FORMS;
import CLASES.Proveedor;
import CLASES.Laboratorio;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MENECES
 */
public class formproveedor extends javax.swing.JInternalFrame {

    /** Creates new form formproveedor */
    public formproveedor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtnBuscar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();
        jbtnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtLaboratorio = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        jbtnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaproveedor = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        txtCod = new javax.swing.JTextField();
        lblcod = new javax.swing.JLabel();
        label = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        jbtnBuscar.setText("Buscar");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, -1));

        jbtnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Delete v2.png"))); // NOI18N
        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 120, 30));

        jbtnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Writing pencil.png"))); // NOI18N
        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, 30));

        jbtnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Edit (Spencil).png"))); // NOI18N
        jbtnNuevo.setText("Nuevo");
        jbtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 120, 30));

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 36));
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("REGISTRO PROVEEDOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 360, -1));

        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Nit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 40, 20));

        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Laboratorio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Nombre");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Telefono");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 160, -1));
        getContentPane().add(txtNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 160, -1));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 160, -1));
        getContentPane().add(txtLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 160, -1));

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 260, -1));

        jbtnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Save file.png"))); // NOI18N
        jbtnGuardar.setText("Guardar");
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 120, 30));

        tablaproveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Nit", "Direccion", "Telefono", "Laboratorio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaproveedorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaproveedor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 650, 340));

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Paterno");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        jRadioButton2.setText("Nombre");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));
        getContentPane().add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 60, -1));

        lblcod.setForeground(new java.awt.Color(255, 51, 0));
        lblcod.setText("Codigo");
        getContentPane().add(lblcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        label.setForeground(new java.awt.Color(255, 51, 0));
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carbon Fiber 1600x1000.jpg"))); // NOI18N
        label.setText("jLabel8");
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
        Proveedor clt=new Proveedor();
        clt.Nombre(txtNombre.getText());
        clt.Nit(txtNit.getText());
        clt.Direccion(txtDireccion.getText());
        clt.Telefono(txtTelefono.getText());
        clt.CodigoLaboratorio(txtLaboratorio.getText());
        clt.Guardar();
        jbtnNuevoActionPerformed(evt);
        JOptionPane.showMessageDialog(null, "Se guardo satisfactoriamente");
        jbtnBuscarActionPerformed(evt);
}//GEN-LAST:event_jbtnGuardarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtBuscarActionPerformed

    private void tablaproveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaproveedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            txtCod.setVisible(true);
            lblcod.setVisible(true);
            int fila = tablaproveedor.getSelectedRow();
            if (fila >= 0 && tablaproveedor.getValueAt(fila, 0) != null) {
                txtCod.setText(String.valueOf(tablaproveedor.getValueAt(fila, 0)));
                txtNombre.setText((String) tablaproveedor.getValueAt(fila, 1));
                txtNit.setText((String) tablaproveedor.getValueAt(fila, 2));
                txtDireccion.setText((String) tablaproveedor.getValueAt(fila, 3));
                txtTelefono.setText((String) tablaproveedor.getValueAt(fila, 4));
                txtLaboratorio.setText((String) tablaproveedor.getValueAt(fila, 5));

                //this.dispose();
            } else {
                label.setText("");
                txtNombre.setText("");
                txtNit.setText("");
                txtDireccion.setText("");
                txtLaboratorio.setText("");
            }
        }
}//GEN-LAST:event_tablaproveedorKeyPressed

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        try{
            Proveedor proveedor = new Proveedor();
            ResultSet reg = proveedor.BuscarPorNOmbre(txtBuscar.getText());
            String[] columnNames = new  String[]{"Codigo","Nombre","Nit","Direccion","Telefono","Laboratorio"};
            Object[][]data = new Object[25][6];
            int i = 0;
            while (reg.next()){
                data[i][0] = reg.getInt(1);
                data[i][1] = reg.getString(2);
                data[i][2] = reg.getString(3);
                data[i][3] = reg.getString(4);
                data[i][4] = reg.getString(5);
                data[i][5] = reg.getString(6);
                i++;
            }
            DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
            tablaproveedor.setModel(tabla);
        }catch(Exception e){}
}//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        // TODO add your handling code here:
        Proveedor clt=new Proveedor();
        clt.Codigo(Integer.parseInt(txtCod.getText()));
        clt.Nombre(txtNombre.getText());
        clt.Nit(txtNit.getText());
        clt.Direccion(txtDireccion.getText());
        clt.Telefono(txtTelefono.getText());
        clt.CodigoLaboratorio(txtLaboratorio.getText());
        clt.Modificar();
        jbtnBuscarActionPerformed(evt);
        jbtnNuevoActionPerformed(evt);
        JOptionPane.showMessageDialog(null, "Modificacion Correcta!!!");
        txtCod.setVisible(false); lblcod.setVisible(false);
}//GEN-LAST:event_jbtnModificarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        Proveedor clt=new Proveedor();
        clt.Codigo(Integer.parseInt(txtCod.getText()));
        clt.Eliminar();
        jbtnNuevoActionPerformed(evt);
        jbtnBuscarActionPerformed(evt);
}//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNuevoActionPerformed
        // TODO add your handling code here:
        txtCod.setText("");
        txtNombre.setText("");
        txtNit.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");
        txtLaboratorio.setText("");
}//GEN-LAST:event_jbtnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JButton jbtnNuevo;
    private javax.swing.JLabel label;
    private javax.swing.JLabel lblcod;
    private javax.swing.JTable tablaproveedor;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtLaboratorio;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}
