/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FORM_VENTAS.java
 *
 * Created on 01-dic-2012, 10:44:49
 */

package FORMS;
import CLASES.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Gonzalo
 */
public class FORM_VENTAS extends javax.swing.JInternalFrame {

    /** Creates new form FORM_VENTAS */
    public FORM_VENTAS() {
        initComponents();
        txtClienteCodigo.setVisible(false);
        txtEmpleadoCodigo.setVisible(false);
        txtCodEmpleado.setVisible(false);
        Calendar Cal= Calendar.getInstance();
        String fec= Cal.get(Cal.DATE)+"/"+(Cal.get(Cal.MONTH)+1)+"/"+Cal.get(Cal.YEAR);
        lblhora.setText(fec);
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClienteCodigo = new javax.swing.JTextField();
        txtEmpleado = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        txtEmpleadoCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMedicamento = new javax.swing.JTable();
        txtCodEmpleado = new javax.swing.JTextField();
        btnEmpleado2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnEmpleado3 = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblhora = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Carbon Fiber 1600x1000.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(51, 51, 51));
        setTitle("Registro de Venta");
        setAutoscrolls(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Cliente:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Empleado:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(txtClienteCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 10, -1));
        getContentPane().add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 160, -1));

        btnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        btnCliente.setText("Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 120, 30));

        jDesktopPane2.setBackground(new java.awt.Color(51, 51, 51));
        jDesktopPane2.setAutoscrolls(true);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FBE.GIF"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBounds(0, -10, 460, 600);
        jDesktopPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 460, 550));
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 160, -1));
        getContentPane().add(txtEmpleadoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 10, -1));

        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("Total:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, -1, -1));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 260, -1));

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 440, -1));

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio", "Cantidad", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalle.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaDetalleKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDetalle);
        tablaDetalle.getColumnModel().getColumn(0).setMaxWidth(50);
        tablaDetalle.getColumnModel().getColumn(1).setMaxWidth(300);
        tablaDetalle.getColumnModel().getColumn(2).setMaxWidth(120);
        tablaDetalle.getColumnModel().getColumn(3).setMaxWidth(120);
        tablaDetalle.getColumnModel().getColumn(4).setMaxWidth(70);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 490, 120));

        tablaMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio ", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaMedicamento.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicamentoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMedicamento);
        tablaMedicamento.getColumnModel().getColumn(0).setMaxWidth(45);
        tablaMedicamento.getColumnModel().getColumn(1).setMaxWidth(900);
        tablaMedicamento.getColumnModel().getColumn(2).setMaxWidth(80);
        tablaMedicamento.getColumnModel().getColumn(3).setMaxWidth(80);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 140));
        getContentPane().add(txtCodEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        btnEmpleado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/buscar.png"))); // NOI18N
        btnEmpleado2.setText("Empleado");
        btnEmpleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleado2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 120, 30));

        jLabel6.setFont(new java.awt.Font("Consolas", 1, 18));
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("DETALLE DE VENTA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        btnEmpleado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Save file.png"))); // NOI18N
        btnEmpleado3.setText("GUARDAR");
        btnEmpleado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleado3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 130, 30));

        txtTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTotalKeyPressed(evt);
            }
        });
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 100, -1));

        jLabel4.setForeground(new java.awt.Color(51, 204, 0));
        jLabel4.setText("Buscar Medicamentos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lblhora.setFont(new java.awt.Font("Consolas", 1, 14));
        lblhora.setForeground(new java.awt.Color(255, 0, 51));
        lblhora.setText("Fecha");
        getContentPane().add(lblhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int codCliente;
private int codEmpleado;
private int codVenta;


    public void Buscar() {
        Medicamento medicamento = new Medicamento();
        boolean sw = false;
        if (jComboBox1.getItemCount() > 1) {
            sw = true;
            try {
                if(jComboBox1.getSelectedItem()=="Ninguno")
                {
                    String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                    int i=0;
                    Object[][] data = new Object[25][4];
                    while(i<25){
                     data[i][0] = "";
                    data[i][1] = "";
                    data[i][2] = "";
                    data[i][3] = "";
                    i++;
                    }
                    DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);
                }
                else{
                int key = ((Categoria) jComboBox1.getSelectedItem()).Codigo();
                ResultSet reg = medicamento.traerMedicamento(txtBuscar.getText(), String.valueOf(key), sw);
                String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                Object[][] data = new Object[500][4];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getDouble(3);
                    data[i][3] = reg.getInt(4);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);}

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        } 
    }
    
    ArrayList lista = new ArrayList();
    public void SeleccionarAlDetalle() {
        int fila = tablaMedicamento.getSelectedRow();
        if (fila < 0 && !lista.contains(tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0))) {
            return;
        }
        Object[][] data = new Object[tablaDetalle.getRowCount() + 1][5];
        int i = 0;
        while (i < tablaDetalle.getRowCount()) {
            data[i][0] = tablaDetalle.getValueAt(i, 0);
            data[i][1] = tablaDetalle.getValueAt(i, 1);
            data[i][2] = tablaDetalle.getValueAt(i, 2);
            data[i][3] = tablaDetalle.getValueAt(i, 3);
            data[i][4] = tablaDetalle.getValueAt(i, 4);
            i++;
        }
        if (!lista.contains(tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0))) {
            lista.add(tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0));
            data[i][0] = tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 0);
            data[i][1] = tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 1);
            data[i][2] = tablaMedicamento.getValueAt(tablaMedicamento.getSelectedRow(), 2);
            data[i][3] = 1;
        } else {
            return;//new Object[][]{}
        }
        String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Cantidad","Sub Total"};
        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
                data, columnNames) {

            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class,java.lang.Double.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });

    }
    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        // TODO add your handling code here:
        BuscarCliente f = new BuscarCliente();
        f.txtCliente = this.txtCliente;
        f.txtClienteCodigo = this.txtClienteCodigo;
        jDesktopPane2.add(f);
        f.show(true);

}//GEN-LAST:event_btnClienteActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try{
            Categoria c = new Categoria();
            jComboBox1.addItem("Ninguno");
            ResultSet reg = c.traerCategoria();
            while(reg.next()){
                jComboBox1.addItem(new Categoria(reg.getInt(1), reg.getString(2)));
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameOpened

    public void buscar2(){
        try{
            Medicamento medicamento =new Medicamento();
            ResultSet reg = medicamento.traerMed(txtBuscar.getText());
                String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                Object[][] data = new Object[500][4];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    data[i][2] = reg.getDouble(3);
                    data[i][3] = reg.getInt(4);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);}

            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }
    private void btnEmpleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleado2ActionPerformed
        // TODO add your handling code here:
        BuscarEmpleado fe=new BuscarEmpleado();
        fe.txtEmpleado=this.txtEmpleado;
        fe.txtCodEmpleado = this.txtCodEmpleado;
        jDesktopPane2.add(fe);
        fe.show(true);

    }//GEN-LAST:event_btnEmpleado2ActionPerformed

    Medicamento m = new Medicamento();
    private void tablaDetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaDetalleKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == 10){
            String cant = String.valueOf(tablaDetalle.getValueAt(tablaDetalle.getSelectedRow(),3));
            if(cant.equals(""))
                cant = "0";
            if(!m.StockSuficiente(String.valueOf(tablaDetalle.getValueAt(tablaDetalle.getSelectedRow(),0)),cant)){
                JOptionPane.showMessageDialog(null, "Stock Insuficiente");
                tablaDetalle.setValueAt(1, tablaDetalle.getSelectedRow(),3);
            }
            double total = 0;
            int i = 0;
            while(i < tablaDetalle.getRowCount()){
               total += Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2)));
               tablaDetalle.setValueAt(Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2))), i, 4);
                i++;
            }
           txtTotal.setText(String.valueOf(total));
        }

    }//GEN-LAST:event_tablaDetalleKeyReleased
Venta venta = new Venta();
DetalleVenta detalle = new DetalleVenta();
    private void btnEmpleado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleado3ActionPerformed
        // TODO add your handling code here:
        if(tablaDetalle.getRowCount() > 0){
        venta.Cod_clt(Integer.parseInt(txtClienteCodigo.getText()));
        venta.Cod_emp(Integer.parseInt(txtCodEmpleado.getText()));
        venta.Guardar();
        int i = 0;
            while(i < tablaDetalle.getRowCount()){
                detalle.CodigoMedicamento(Integer.parseInt(String.valueOf(tablaDetalle.getValueAt(i,0))));
                detalle.Cantidad(Integer.parseInt(String.valueOf(tablaDetalle.getValueAt(i,3))));
                detalle.precio(Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2))));
                detalle.Guardar();
                i++;
            }
        JOptionPane.showMessageDialog(null, "Venta Realizada Correctamente");
        }
    }//GEN-LAST:event_btnEmpleado3ActionPerformed

    private void txtTotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTotalKeyPressed
    public void cargarSubTotal(){
        String cant = String.valueOf(tablaDetalle.getValueAt(tablaDetalle.getSelectedRow(),3));
            if(cant.equals(""))
                cant = "0";
            if(!m.StockSuficiente(String.valueOf(tablaDetalle.getValueAt(tablaDetalle.getSelectedRow(),0)),cant)){
                JOptionPane.showMessageDialog(null, "Stock Insuficiente");
                tablaDetalle.setValueAt(1, tablaDetalle.getSelectedRow(),3);
            }
            double total = 0;
            int i = 0;
            while(i < tablaDetalle.getRowCount()){
               total += Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2)));
               tablaDetalle.setValueAt(Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2))), i, 4);
                i++;
            }
           txtTotal.setText(String.valueOf(total));
    }
    
    private void tablaMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicamentoMouseClicked
        // TODO add your handling code here:
        SeleccionarAlDetalle();
        int i = 0;
        double total=0;
            while(i < tablaDetalle.getRowCount()){
               total += Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2)));
               tablaDetalle.setValueAt(Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,3))) * Double.parseDouble(String.valueOf(tablaDetalle.getValueAt(i,2))), i, 4);
                i++;
            }
           txtTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_tablaMedicamentoMouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
            txtBuscar.setText("");
        Buscar();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
         if(jComboBox1.getSelectedItem()=="Ninguno"){
            buscar2();
        }
        else{
        Buscar();}
         if(txtBuscar.getText().length()==0){
                String[] columnNames = new String[]{"Codigo", "Nombre", "Precio", "Stock"};
                    int i=0;
                    Object[][] data = new Object[50][4];
                    while(i<50){
                     data[i][0] = "";
                    data[i][1] = "";
                    data[i][2] = "";
                    data[i][3] = "";
                    i++;
                    }
                    DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablaMedicamento.setModel(tabla);
            }
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEmpleado2;
    private javax.swing.JButton btnEmpleado3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblhora;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaMedicamento;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtClienteCodigo;
    private javax.swing.JTextField txtCodEmpleado;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtEmpleadoCodigo;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

}
