/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FromCategoria.java
 *
 * Created on 08-12-2012, 11:01:29 AM
 */

package FORMS;

import CLASES.*;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author MENECES
 */
public class FromCategoria extends javax.swing.JInternalFrame {

    /** Creates new form FromCategoria */
    public FromCategoria() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttnGuardar = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtcod = new javax.swing.JTextField();
        bttnModificar = new javax.swing.JButton();
        bttnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacategoria = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttnGuardar.setText("Guardar");
        bttnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 12, 160, -1));
        getContentPane().add(txtcod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        bttnModificar.setText("Modificar");
        bttnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, -1));

        bttnEliminar.setText("Eliminar");
        bttnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(bttnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        tablacategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablacategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablacategoriaMouseClicked(evt);
            }
        });
        tablacategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablacategoriaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablacategoria);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 190, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void limpiar(){
        txtcod.setText("");
        txtnombre.setText("");
    }
    private void bttnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGuardarActionPerformed
        // TODO add your handling code here:
        Categoria cat = new Categoria();
        cat.Nombre(txtnombre.getText());
        cat.Guardar();
        limpiar();
        buscar();
    }//GEN-LAST:event_bttnGuardarActionPerformed

    private void bttnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnModificarActionPerformed
        // TODO add your handling code here:
        Categoria cat = new Categoria();
        cat.Codigo(Integer.parseInt(txtcod.getText()));
        cat.Nombre(txtnombre.getText());
        cat.Modificar();
        limpiar();
        buscar();
    }//GEN-LAST:event_bttnModificarActionPerformed

    private void bttnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEliminarActionPerformed
        // TODO add your handling code here:
        Categoria cat = new Categoria();
        cat.Codigo(Integer.parseInt(txtcod.getText()));
        cat.Eliminar();
        limpiar();
        buscar();
    }//GEN-LAST:event_bttnEliminarActionPerformed

    private void tablacategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablacategoriaMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tablacategoriaMouseClicked
    void buscar(){
         try{
        Categoria cat = new Categoria();
        ResultSet reg = cat.traerCategoria();
        String[] columnNames = new String[]{"Codigo", "Nombre"};
                Object[][] data = new Object[50][2];
                int i = 0;
                while (reg.next()) {
                    data[i][0] = reg.getInt(1);
                    data[i][1] = reg.getString(2);
                    i++;
                }
                DefaultTableModel tabla = new DefaultTableModel(data, columnNames);
                tablacategoria.setModel(tabla);}
          catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
    }
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_formInternalFrameOpened

    private void tablacategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablacategoriaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==10){
            int fila = tablacategoria.getSelectedRow();
        if(fila >= 0 && tablacategoria.getValueAt(fila, 0) != null)
        {
            txtcod.setText(String.valueOf(tablacategoria.getValueAt(fila, 0)));
            txtnombre.setText((String)tablacategoria.getValueAt(fila, 1));
            //this.dispose();
        }
        else
        {
            txtcod.setText("");
            txtnombre.setText("");
        }
        }
    }//GEN-LAST:event_tablacategoriaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnEliminar;
    private javax.swing.JButton bttnGuardar;
    private javax.swing.JButton bttnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablacategoria;
    private javax.swing.JTextField txtcod;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

}
